using System;

namespace ProjectWorlds.PermutationNoise
{
    public abstract class PermutationNoise
    {
        // The seed for the noise
        public uint Seed
        {
            get
            {
                return seed;
            }
        }
        protected uint seed;

        // The number of points queried since the last seed change
        public uint Count
        {
            get
            {
                return count;
            }
        }
        protected uint count;

        // The last value that was generated by the class [0, 1]
        public float CurrentValue { get; set; }

        public abstract void SetSeed(int seed);

        public PermutationNoise() : this((uint)DateTime.Now.Ticks)
        {

        }

        public PermutationNoise(uint seed)
        {
            this.seed = seed;
            count = 0;
            CurrentValue = 0;
        }

        // Returns the next value in the noise sequence
        public abstract float NextValue();

        // Generate the next value in the noise sequence [0, x]
        public abstract float NextValue(float x);

        // Generate the next value in the noise sequence [x, y]
        public abstract float NextValue(float x, float y);

        // Reset the noise sequence
        public abstract void Reset();
    }
}